[tox]
envlist = py313,py314,lint
isolated_build = true

[testenv]
runner = uv-venv-runner
extras = dev
commands = pytest -v {posargs}

[testenv:lint]
basepython = py313
extras = dev
commands =
    ruff check src tests
    ruff format --check src tests
    ty check src
